name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Pull image from GitHub Packages
        run: docker pull ghcr.io/cghinami/vcml-pydrofoil:latest

      - name: Tag image for local script compatibility
        run: docker tag ghcr.io/cghinami/vcml-pydrofoil:latest vcml-pydrofoil:latest

      - name: Make script executable
        run: chmod +x container_run_simulator.sh

      - name: Run test
        run: timeout 30 ./container_run_simulator.sh docker
